on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.11.0

      - run: npm ci
      - run: npm run -w twrl build

      # Here we set an empty base, which makes vite produce links that are relative
      # to the assets, as opposed to expecting all assets to be served from `/`.
      - run: npm run -w twrl-website build -- --base ''

      # XXX: this doesn't use any BASE_URL (like e.g. '/twrl') because
      # the primary URL is the website, not github.io/twrl
      - uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./packages/twrl-website/dist

  deploy:
    if: github.ref == 'ref/head/main'
    runs-on: ubuntu-latest
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
